In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist

np.random.seed(2)

In [3]:
means = [[2, 2], [4, 2]]
cov = [[0.3, 0.2], [0.2, 0.3]]
N = 20
X0 = np.random.multivariate_normal(means[0], cov, N).T
X1 = np.random.multivariate_normal(means[1], cov, N).T

In [5]:
X0

array([[2.11200125, 1.3085396 , 2.51153392, 1.04405478, 2.15254162,
        1.68244384, 1.58334917, 2.63624444, 1.85831694, 1.93727986,
        1.33290958, 2.4697242 , 1.57395371, 0.98379239, 2.49008239,
        2.28779706, 2.58326845, 2.2536685 , 2.55700152, 1.05419243],
       [2.07746801, 1.86675739, 1.89235835, 1.58870979, 2.30946373,
        1.93568992, 2.21244285, 3.10171506, 1.76121109, 0.88918865,
        1.50556893, 2.66340908, 2.73013273, 1.18087489, 2.22917145,
        2.03725257, 2.31897762, 2.02251099, 2.14158843, 0.39536933]])

In [6]:
X1

array([[4.41402075, 4.06701995, 3.318081  , 3.84622929, 3.84007596,
        4.16860578, 4.39809886, 3.86358184, 4.55199165, 3.72274273,
        4.76570368, 5.23903244, 2.14303611, 3.19963387, 3.49595399,
        3.69842381, 4.57690315, 3.60023117, 3.50237903, 3.22915814],
       [2.60739398, 2.25656012, 1.882739  , 1.40180586, 1.05078076,
        1.94581551, 2.66270017, 2.31967474, 2.93047383, 1.77931712,
        2.65310687, 2.30764218, 0.57721849, 1.00777328, 1.80784803,
        1.70006038, 1.65134441, 1.78962474, 1.37973424, 1.02902967]])

In [8]:
X = np.concatenate((X0,X1), axis=1)
X

array([[2.11200125, 1.3085396 , 2.51153392, 1.04405478, 2.15254162,
        1.68244384, 1.58334917, 2.63624444, 1.85831694, 1.93727986,
        1.33290958, 2.4697242 , 1.57395371, 0.98379239, 2.49008239,
        2.28779706, 2.58326845, 2.2536685 , 2.55700152, 1.05419243,
        4.41402075, 4.06701995, 3.318081  , 3.84622929, 3.84007596,
        4.16860578, 4.39809886, 3.86358184, 4.55199165, 3.72274273,
        4.76570368, 5.23903244, 2.14303611, 3.19963387, 3.49595399,
        3.69842381, 4.57690315, 3.60023117, 3.50237903, 3.22915814],
       [2.07746801, 1.86675739, 1.89235835, 1.58870979, 2.30946373,
        1.93568992, 2.21244285, 3.10171506, 1.76121109, 0.88918865,
        1.50556893, 2.66340908, 2.73013273, 1.18087489, 2.22917145,
        2.03725257, 2.31897762, 2.02251099, 2.14158843, 0.39536933,
        2.60739398, 2.25656012, 1.882739  , 1.40180586, 1.05078076,
        1.94581551, 2.66270017, 2.31967474, 2.93047383, 1.77931712,
        2.65310687, 2.30764218, 0.57721849, 1.0

In [9]:
Y = np.concatenate((np.ones((1, N)), -1 * np.ones((1, N))), axis=1)
Y

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1.]])

In [10]:
def h(W,x):
    return np.sign(np.dot(W.T, x))

In [17]:
def has_converged(X, y, W):
    return np.array_equal(h(W, X), y)

def perceptron(X, y, w_init):
    W = [w_init]
    N = X.shape[1]
    d = X.shape[0]
    miss_points = []
    while True:
        mix_id = np.random.permutation(N)
        for i in range(N):
            xi = X[:, mix_id[i]].reshape(d, 1)
            yi = y[0, mix_id[i]]
            if h(W[-1], xi) != yi:
                miss_points.append(mix_id[i])
                w_new = W[-1] + yi * xi
                print('miss points:', miss_points)
        if has_converged(X, y, W[-1]):
            break
    return (W, miss_points)

In [ ]:
d = X.shape[0]
w_init = np.random.randn(d, 1)
(w, m) = perceptron(X,Y, w_init)